//TODO common action and respective pages Actions will be in Seprate Page

export const ADD_FILTER = 'ADD_FILTER'

export const SET_USER_IMG = 'SET_USER_IMG'
export const SET_USER_NAME = 'SET_USER_NAME'
// Actions for Filter+Grid Pages
export const FETCH_LIST_DATA = 'FETCH_LIST_DATA'
export const FETCH_LIST_DATA_API = 'FETCH_LIST_DATA_API'
export const FILTER = 'FILTER'
export const FILTER_CHANGE_API = 'FILTER_CHANGE_API'
export const FILTER_CHANGE_API_DATA = 'FILTER_CHANGE_API_DATA'
export const FILTER_SELECT_ALL = 'FILTER_SELECT_ALL'
export const FILTER_CLEAR = 'FILTER_CLEAR'
export const FILTER_CLEAR_ALL = 'FILTER_CLEAR_ALL'
export const FILTER_TYPEAHEAD = 'FILTER_TYPEAHEAD'
export const GRID_SORT = 'GRID_SORT'
export const GRID_SORT_API = 'GRID_SORT_API'
export const GRID_SORT_API_DATA = 'GRID_SORT_API_DATA'
export const GRID_BULK_INITIATE = 'GRID_BULK_INITIATE'
export const GRID_COLUMN_DISPLAY_CHANGE = 'GRID_COLUMN_DISPLAY_CHANGE'
export const GRID_COLUMN_REORDER = 'GRID_COLUMN_REORDER'
export const UPDATE_FILTER = 'UPDATE_FILTER'
export const FETCH_PAGINATED_DATA_API = 'FETCH_PAGINATED_DATA_API'
export const FETCH_TYPEAHEAD_DATA_API = 'FETCH_TYPEAHEAD_DATA_API'
export const FILTER_CAT_CHANGE = 'FILTER_CAT_CHANGE'

export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION'
//for AddManual Device
export const DEVICE_PRODUCT_NAME = 'DEVICE_PRODUCT_NAME'
//Common for Resetting the Form
export const RESET = 'RESET'
//Async actions for normal Pages and Form
export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA = 'RECV_DATA';
//Async actions for dialog Pages and Form
export const DIALOG_RECV_ERROR = 'DIALOG_RECV_ERROR';
export const DIALOG_REQ_DATA = 'DIALOG_REQ_DATA';
export const DIALOG_RECV_DATA = 'DIALOG_RECV_DATA';
//Action for Add Manual Device
export const RECV_SITE_DATA = 'RECV_SITE_DATA';
export const SUBMIT_MANUAL_DEVICE = 'SUBMIT_MANUAL_DEVICE';

//Get the user role info
export const UPDATE_USER_MENUS = 'UPDATE_USER_MENUS';
export const UPDATE_ORGANIZATION_INFO = 'UPDATE_ORGANIZATION_INFO';
export const UPDATE_SENTIENCE_URL = 'UPDATE_SENTIENCE_URL';

//Get Notification Message
export const NOTIFICATION_MESSAGE = 'NOTIFICATION_MESSAGE';

//Add Gateway Device
export const ADD_NEW_DEVICE = 'ADD_NEW_DEVICE'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const COPY_BILLING_ADDRESS = 'COPY_BILLING_ADDRESS'

export const DIALOG_SHOW = 'DIALOG_SHOW'
export const DIALOG_SHOW_FOR_POPUP = 'DIALOG_SHOW_FOR_POPUP'

export const DIALOG_HIDE = 'DIALOG_HIDE'
export const DIALOG_HIDE_FOR_POPUP = 'DIALOG_HIDE_FOR_POPUP'
export const CHANGE_ORG_ID_SITE = 'CHANGE_ORG_ID_SITE'
export const CHANGE_SENTIENCE_URL = 'CHANGE_SENTIENCE_URL'


export const COUNTRY_LIST_DATA = 'COUNTRY_LIST_DATA'
export const DISPLAY_COUNTRY_LIST = 'DISPLAY_COUNTRY_LIST'
export const STATE_LIST_DATA = 'STATE_LIST_DATA'

export const CHANGE_ORG_ID_ZONE = 'CHANGE_ORG_ID_ZONE'
export const CHANGE_SITE_ID_ZONE = 'CHANGE_SITE_ID_ZONE'

export const UPDATE_SITE_ID = 'UPDATE_SITE_ID'

export const SET_NAVIGATION = 'SET_NAVIGATION'
export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB'
export const UPDATE_SITE_SELECTOR = 'UPDATE_SITE_SELECTOR'
export const ADD_SITE_SELECTOR = 'ADD_SITE_SELECTOR'

//Add calibration details

export const UPDATE_GATEWAY_ID = 'UPDATE_GATEWAY_ID'
export const SET_NAVIGATION_PARAMS = 'SET_NAVIGATION_PARAMS'


// Notification Event Types
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED'
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE'
export const UPDATE_SITE_SELECTOR_LABEL = 'UPDATE_SITE_SELECTOR_LABEL'
export const NOTIFICATION_QUEUE_DATA_RECEIVED = 'NOTIFICATION_QUEUE_DATA_RECEIVED'

//History action Types
export const LOG_FILTER_CHANGE = 'LOG_FILTER_CHANGE'
export const LOG_FILTER_CHANGE_DATA = 'LOG_FILTER_CHANGE_DATA'
export const LOG_SUMMARY_DETAILS = 'LOG_SUMMARY_DETAILS'
export const LOG_SUMMARY_DETAILS_COPY = 'LOG_SUMMARY_DETAILS_COPY'
export const LOG_SUMMARY_DETAILS_RESET = 'LOG_SUMMARY_DETAILS_RESET'
export const UPDATE_DEVICE_DATA_LOG = 'UPDATE_DEVICE_DATA_LOG'
export const UPDATE_DATA_LOG_MODAL_STATE = 'UPDATE_DATA_LOG_MODAL_STATE'

export const MANUAL_REFRESH_NOTIFICATION = 'MANUAL_REFRESH_NOTIFICATION'
export const MANUAL_REFRESH_CLICKED = 'MANUAL_REFESH_CLICKED'
export const REFRESH_LOGS = 'REFRESH_LOGS'


//Notification Manager
export const ACTION_INITIATED = 'ACTION_INITIATED';
export const ACTION_FAILED = 'ACTION_FAILED';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const ACTION_IN_PROGRESS = 'ACTION_IN_PROGRESS';
export const ACTION_TIMED_OUT = 'ACTION_TIMED_OUT';

export const UPDATE_USER_CONTEXT = 'UPDATE_USER_CONTEXT'

export const USER_BULK_ACTION = 'USER_BULK_ACTION';
export const BULK_DATA_CHILD = 'BULK_DATA_CHILD'
export const BULK_DATA_HEADER = 'BULK_DATA_HEADER'

